### ISSUE TITLE
Unexpected token )

### ISSUE THREAD

**Issue by PaulBGD** [webcatalog/electron-widevinecdm#9]
```
error /home/paul/Documents/Coding/node_modules/electron-widevinecdm: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/paul/Documents/Coding/node_modules/electron-widevinecdm
Output:
/home/paul/Documents/Coding/node_modules/electron-widevinecdm/install.js:84
  ),
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Happens upon install.

**Comment by quanglam2807** [comment]
@PaulBGD It seems like the script doesn't work correctly on Node.js 6. Please upgrade to Node.js 8+.

**Comment by quanglam2807** [comment]
@PaulBGD I'll add Node.js 6 support in the next version.

**Comment by PaulBGD** [comment]
I actually thought I was on node 8 already, fixed that on my side.
